### ISSUE TITLE
could not find driver (SQL: select * from information_schema.tables where table_schema = dsa_leave_management and table_name = migrations and table_type = 'BASE TABLE')

### ISSUE THREAD

**Issue by IAMLEIIKUN** [jasonjpulikkottil/leave_management_system#1]
could not find driver (SQL: select * from information_schema.tables where table_schema = dsa_leave_management and table_name = migrations and table_type = 'BASE TABLE')

**Comment by jasonjpulikkottil** [comment]
Please mention steps to reproduce the error.

This error message suggests that there is an issue with the database driver or connection, and that the database cannot be accessed.

Here are a few things you can try to troubleshoot the issue:

    Check if the database credentials are correct and if the database exists: Make sure that the username, password, and database name specified in your application's configuration are correct and that the database actually exists.

    Check if the database driver is installed: Make sure that the appropriate database driver is installed for your application. For example, if you're using MySQL, make sure that the MySQL driver is installed and configured correctly.

    Check if the database server is running: Make sure that the database server is running and accepting connections. You can try connecting to the database using a database client to verify this.

    Check the permissions of the user connecting to the database: Ensure that the user connecting to the database has the necessary permissions to read and write to the database.

    Check for typos in your SQL query: Make sure that your SQL query is correct and that there are no typos in the table names or SQL syntax.

    Restart the server: Sometimes, simply restarting the server or the database can resolve the issue.
